language: node_js
node_js: node
install:
  npm install
  npm install react react-dom
script:
  - npm run build
  - npm test
after_success: npm run coverage-only
cache:
  directories:
    - node_modules